# Min powerlevel to start/end meetings
powerlevel: 50
# Which backend to use
backend: fedora
backend_data: {}
tags:
  action: "ğŸš©"
  info: "âœï¸"
  agreed: "ğŸ‘"
  rejected: "ğŸ‘"
  idea: "ğŸ’­"
  halp: "ğŸ›Ÿ"
  link: "ğŸ”—"
tags_commandprefix: \!
tags_commandatstart: True
